YEARS_DATA: [
  #"2021-22",
  #"2022-23", 
  "2023-24"
  ]

TEAMS_GAME_DATA: [
  #"BOS",
  #"PHI",
  #"MIL",
  #"MIA",
  #"ORL",
  #"NYK",
  #"IND",
  #"CLE",
  #"ATL",
  #"BKN",
  #"TOR",
  #"CHI",
  #"CHA",
  #"WAS",
  #"DET",
  "MIN",
  "OKC",
  "DEN",
  "SAC",
  "DAL",
  "LAL",
  "HOU",
  "PHX",
  "NOP",
  "GSW",
  "LAC",
  "UTA",
  "MEM",
  "POR",
  "SAS"
]

NBA_TEAMS:
  "BOS": 1610612738
  "PHI": 1610612755
  "MIL": 1610612749
  "MIA": 1610612748
  "ORL": 1610612753
  "NYK": 1610612752
  "IND": 1610612754
  "CLE": 1610612739
  "ATL": 1610612737
  "BKN": 1610612751
  "TOR": 1610612761
  "CHI": 1610612741
  "CHA": 1610612766
  "WAS": 1610612764
  "DET": 1610612765
  "MIN": 1610612750
  "OKC": 1610612760
  "DEN": 1610612743
  "SAC": 1610612758
  "DAL": 1610612742
  "LAL": 1610612747
  "HOU": 1610612745
  "PHX": 1610612756
  "NOP": 1610612740
  "GSW": 1610612744
  "LAC": 1610612746
  "UTA": 1610612762
  "MEM": 1610612763
  "POR": 1610612757
  "SAS": 1610612759

FEATURES: [
  "W_PCT",
  "W_RANK",
  "PLUS_MINUS_RANK",
  "PTS_RANK",
  "REB_RANK",
  "AST_RANK",
  "BLK_RANK",
  "TOV_RANK",
  "STL_RANK",
  "FG3A_RANK",
  "FG3_PCT_RANK",
  "FGA_RANK",
  "FG_PCT_RANK",
  "FTA_RANK",
  "FT_PCT_RANK"
] 

FEATURESET_EXTRA_COLUMNS: [
  "MATCHUP",
  "GAME_DATE",
  "WIN",
  "TOTAL_POINTS"
]

GAME_SAMPLE_COLUMNS: [
  "MATCHUP",
  "GAME_DATE",
  "LOCAL_TEAM",
  "AWAY_TEAM",
  "WIN",
  "TOTAL_POINTS"
]

DATA:
  FOLDER_NAME: "data"
  NBA_DATA_RAW_FOLDER: "NBA_RAW_DATA"
  NBA_RAW_FILENAME: "{TEAM}_RAW_DATA.csv"

MODELING:
  TRAINING_YEARS: [2021, 2022]
  TEST_YEARS: [2023]

